MaternKernel:
  coefficient:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  scale:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
  nu:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 3.0
    width_modifier:
      type: Relative
      value: 0.2
    gaussian_limits:
      lower: 0.0
      upper: inf
