SersicCore:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-05
    type: LogUniform
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
SersicCoreSph:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  intensity:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-05
    type: LogUniform
    upper_limit: 1000.0
    width_modifier:
      type: Relative
      value: 0.2
  mass_to_light_ratio:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0e-06
    type: LogUniform
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.3
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5