# These settings specify the default matplotlib settings when "D figures and subplots are plotted.

# For example, the `CriticalCurvePlot` section has the following lines:

# CriticalCurvePlot:
#    figure:
#      c: k,r,g,b,m,y
#    subplot:
#      c: k

# This means that when critical curves are plotted, each one cycles through the colors black, red, green, etc.,
# provided the values of these parameters are not manually set by the user via a `MatPlot2D` object.
#
# In the above example, subplots (e.g. more than one image) will always use `c=k` by default as well.
#
# These configuration options can be customized such that the appearance of figures and subplots for a user is
# optimal for your computer set up.

CausticsPlot:                       # wrapper for `plt.plot()`: customize plots caustics in the source-plane.
  figure:
    c: k,r,g,b,m,y
    linestyle: '-'
    linewidth: 2
  subplot:
    c: k,r,g,b,m,y
    linestyle: '-'
    linewidth: 2
CriticalCurvesPlot:                 # wrapper for `plt.plot()`: customize plots critical curves in the image-plane.
  figure:
    c: k,r,g,b,m,y
    linestyle: '-'
    linewidth: 2
  subplot:
    c: k,r,g,b,m,y
    linestyle: '-'
    linewidth: 2
LightProfileCentresScatter:        # wrapper for `plt.scatter()`: customize the appearance of points showing the light profile centres.
  figure:
    c: k,r,g,b,m,y
    marker: +
    s: 20
  subplot:
    c: r,g,b,m,y,k
    marker: +
    s: 26
MassProfileCentresScatter:         # wrapper for `plt.scatter()`: customize the appearance of points showing the mass profile centres.
  figure:
    c: k,r,g,b,m,y
    marker: x
    s: 20
  subplot:
    c: r,g,b,m,y,k
    marker: x
    s: 26
MultipleImagesScatter:            # wrapper for `plt.scatter()`: customize the appearance of points showing the multiple images of a point source model.
  figure:
    c: k,r,g,b,m,y
    marker: o
    s: 16
  subplot:
    c: r,g,b,m,y,k
    marker: o
    s: 16