analysis:
  preload_attempts: 250
fits:
  flip_for_ds9: true
hyper:
  hyper_minimum_percent: 0.01
  hyper_noise_limit: 100000000.0
  stochastic_outputs: false
test:
  check_figure_of_merit_sanity: false
  bypass_figure_of_merit_sanity: false
  check_preloads: false
  preloads_check_threshold: 0.1     # If the figure of merit of a fit with and without preloads is greater than this threshold, the check preload test fails and an exception raised for a model-fit. 
