radial_minimum:
  radial_minimum:
    chameleon: 1.0e-08
    chameleonsph: 1.0e-08
    devvaucouleurs: 1.0e-06
    devvaucouleurssph: 1.0e-06
    ellexponentialradialgradient: 1.0e-06
    ellprofile: 1.0e-08
    elsonfreefall: 1.0e-08
    elsonfreefallsph: 1.0e-08
    exponential: 1.0e-06
    exponentialcore: 1.0e-06
    exponentialcoresph: 1.0e-06
    exponentialsph: 1.0e-06
    externalshear: 1.0e-08
    gaussian: 1.0e-08
    gaussiansph: 1.0e-08
    gnfw: 1.0e-06
    gnfwmcrludlow: 1.0e-06
    gnfwsph: 1.0e-06
    isothermal: 1.0e-08
    isothermalcore: 1.0e-08
    isothermalcoresph: 1.0e-08
    isothermalinitialize: 1.0e-08
    isothermalsph: 1.0e-08
    masssheet: 1.0e-08
    moffat: 1.0e-08
    moffatsph: 1.0e-08
    nfw: 1.0e-06
    nfwmcrduffysph: 1.0e-06
    nfwmcrludlow: 1.0e-06
    nfwmcrludlowsph: 1.0e-06
    nfwmcrscatterludlow: 1.0e-06
    nfwmcrscatterludlowsph: 1.0e-06
    nfwsph: 1.0e-06
    nfwtruncatedmcrduffysph: 1.0e-06
    nfwtruncatedmcrludlowsph: 1.0e-06
    nfwtruncatedmcrscatterludlowsph: 1.0e-06
    nfwtruncatedsph: 1.0e-06
    pointmass: 1.0e-08
    powerlaw: 1.0e-08
    powerlawbroken: 1.0e-08
    powerlawbrokensph: 1.0e-08
    powerlawcore: 1.0e-08
    powerlawcoresph: 1.0e-08
    powerlawsph: 1.0e-08
    sersic: 1.0e-06
    sersiccore: 1.0e-06
    sersiccoresph: 1.0e-06
    sersicradialgradient: 1.0e-06
    sersicsph: 1.0e-06
    sphexponentialradialgradient: 1.0e-06
    sphsersicradialgradient: 1.0e-06
