model.Planck15FlatwCDM:
  Om0:
    gaussian_limits:
      lower: '0.0486'
      upper: '1.0'
    lower_limit: '0.0486'
    type: Uniform
    upper_limit: '1.0'
    width_modifier:
      type: Absolute
      value: 0.3
  w0:
    gaussian_limits:
      lower: '-2.0'
      upper: '0.0'
    lower_limit: '-2.0'
    type: Uniform
    upper_limit: '0.0'
    width_modifier:
      type: Absolute
      value: 0.5
model.Planck15Om0:
  Om0:
    gaussian_limits:
      lower: '0.0486'
      upper: '1.0'
    lower_limit: '0.0486'
    type: Uniform
    upper_limit: '1.0'
    width_modifier:
      type: Absolute
      value: 0.3
