chameleon.Chameleon:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  core_radius_0:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
  core_radius_1:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
chameleon.ChameleonSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  core_radius_0:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
  core_radius_1:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Absolute
      value: 0.3
dev_vaucouleurs.DevVaucouleurs:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
dev_vaucouleurs.DevVaucouleursSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
eff.ElsonFreeFall:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  eta:
    gaussian_limits:
      lower: 0.0
      upper: 5.0
    lower_limit: 0.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 1.5
eff.ElsonFreeFallSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  eta:
    gaussian_limits:
      lower: 0.0
      upper: 5.0
    lower_limit: 0.5
    type: Uniform
    upper_limit: 3.0
    width_modifier:
      type: Absolute
      value: 1.5
exponential.Exponential:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
exponential.ExponentialSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
exponential_core.ExponentialCore:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
exponential_core.ExponentialCoreSph:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
gaussian.Gaussian:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  sigma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
gaussian.GaussianSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  sigma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
moffat.Moffat:
  alpha:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
  beta:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Relative
      value: 0.5
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
moffat.MoffatSph:
  alpha:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 1.0
    width_modifier:
      type: Relative
      value: 0.5
  beta:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 1.0
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Relative
      value: 0.5
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
sersic.Sersic:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic.SersicSph:
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_core.SersicCore:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  ell_comps_0:
    gaussian_limits:
      lower: -1.0
      upper: 1.0
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  ell_comps_1:
    gaussian_limits:
      lower: '-1.0'
      upper: '1.0'
    lower_limit: -1.0
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.2
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
sersic_core.SersicSphCore:
  alpha:
    gaussian_limits:
      lower: 4.5
      upper: 5.5
    lower_limit: 4.5
    type: Uniform
    upper_limit: 5.5
    width_modifier:
      type: Absolute
      value: 3.0
  centre_0:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  centre_1:
    gaussian_limits:
      lower: -inf
      upper: inf
    lower_limit: -inf
    mean: 0.0
    sigma: 0.3
    type: Gaussian
    upper_limit: inf
    width_modifier:
      type: Absolute
      value: 0.05
  effective_radius:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 30.0
    width_modifier:
      type: Relative
      value: 1.0
  gamma:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 0.5
    width_modifier:
      type: Absolute
      value: 0.1
  radius_break:
    gaussian_limits:
      lower: 0.0
      upper: inf
    lower_limit: 0.0
    type: Uniform
    upper_limit: 10.0
    width_modifier:
      type: Absolute
      value: 0.1
  sersic_index:
    gaussian_limits:
      lower: 0.8
      upper: 5.0
    lower_limit: 0.8
    type: Uniform
    upper_limit: 5.0
    width_modifier:
      type: Absolute
      value: 1.5
